version: "3.7"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "9929:9929"
      - "9230:9230"
    volumes:
      #- /app/node_modules
      - ./src:/app/src
    environment:
      - NODE_ENV=development
      - GATSBY_WEBPACK_PUBLICPATH=/
