version: "3.7"

services:
  develop:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gatsby-blog
    command: sh -c "npm install && gatsby develop -H 0.0.0.0 -p 8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: always